spring.application.name=hospitalManagement

spring.datasource.url=jdbc:mysql://localhost:3306/hospitalDB
spring.datasource.username=root
spring.datasource.password=mysqlS@1806
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true