spring.application.name=hospitalManagement

spring.datasource.url=jdbc:mysql://localhost:3306/hospitalDB
spring.datasource.username=root
spring.datasource.password=mysqlS@1806
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# The following properties are used to add the data.sql file to the database when the application starts. 
# like adding dummy data to the database when the application starts. This is useful for testing purposes.
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
